In [5]:
# Data Manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Feature Scaling
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Ignore Warnings
import warnings
warnings.filterwarnings("ignore")

In [6]:
train = pd.read_csv(r"D:\Project\aircraft maintenance system\data\processed\train_clean.csv", index_col=0)

train.head(10)

,cycle,setting1,setting2,setting3,s1,s2,s3,s4,s5,s6,...,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21
unit,,,,,,,,,,,,,,,,,,,,,
1,1,42.0049,0.8400,100.0,445.00,549.68,1343.43,1112.93,3.91,5.70,...,129.78,2387.99,8074.83,9.3335,0.02,330,2212,100.00,10.62,6.3670
1,2,20.0020,0.7002,100.0,491.19,606.07,1477.61,1237.50,9.35,13.61,...,312.59,2387.73,8046.13,9.1913,0.02,361,2324,100.00,24.37,14.6552
1,3,42.0038,0.8409,100.0,445.00,548.95,1343.12,1117.05,3.91,5.69,...,129.62,2387.97,8066.62,9.4007,0.02,329,2212,100.00,10.48,6.4213
1,4,42.0000,0.8400,100.0,445.00,548.70,1341.24,1118.03,3.91,5.70,...,129.80,2388.02,8076.05,9.3369,0.02,328,2212,100.00,10.54,6.4176
1,5,25.0063,0.6207,60.0,462.54,536.10,1255.23,1033.59,7.05,9.00,...,164.11,2028.08,7865.80,10.8366,0.02,305,1915,84.93,14.03,8.6754
1,6,34.9996,0.8400,100.0,449.44,554.77,1352.87,1117.01,5.48,7.97,...,181.90,2387.87,8054.10,9.3346,0.02,330,2223,100.00,14.91,8.9057
1,7,0.0019,0.0001,100.0,518.67,641.83,1583.47,1393.89,14.62,21.58,...,520.48,2387.89,8127.92,8.3960,0.03,391,2388,100.00,38.93,23.4578
1,8,41.9981,0.8400,100.0,445.00,549.05,1344.16,1110.77,3.91,5.69,...,129.65,2387.97,8075.99,9.3679,0.02,329,2212,100.00,10.55,6.2787
1,9,42.0016,0.8400,100.0,445.00,549.55,1342.85,1101.67,3.91,5.70,...,129.65,2388.00,8071.13,9.3384,0.02,328,2212,100.00,10.63,6.3055
1,10,25.0019,0.6217,60.0,462.54,536.35,1251.91,1041.37,7.05,9.01,...,164.08,2028.13,7869.41,10.9141,0.02,305,1915,84.93,14.34,8.6119

In [7]:
# Find the maximum operating cycle for each engine
max_cycle = train.groupby("unit")["cycle"].max().reset_index()
max_cycle.columns = ["unit", "max_cycle"]

# Display first few rows
max_cycle.head()

   unit  max_cycle
0     1        321
1     2        299
2     3        307
3     4        274
4     5        193

In [8]:

# Merge maximum cycle information with the original dataset
train = train.merge(max_cycle, on="unit")

train.head()

,unit,cycle,setting1,setting2,setting3,s1,s2,s3,s4,s5,...,s13,s14,s15,s16,s17,s18,s19,s20,s21,max_cycle
0,1,1,42.0049,0.8400,100.0,445.00,549.68,1343.43,1112.93,3.91,...,2387.99,8074.83,9.3335,0.02,330,2212,100.00,10.62,6.3670,321
1,1,2,20.0020,0.7002,100.0,491.19,606.07,1477.61,1237.50,9.35,...,2387.73,8046.13,9.1913,0.02,361,2324,100.00,24.37,14.6552,321
2,1,3,42.0038,0.8409,100.0,445.00,548.95,1343.12,1117.05,3.91,...,2387.97,8066.62,9.4007,0.02,329,2212,100.00,10.48,6.4213,321
3,1,4,42.0000,0.8400,100.0,445.00,548.70,1341.24,1118.03,3.91,...,2388.02,8076.05,9.3369,0.02,328,2212,100.00,10.54,6.4176,321
4,1,5,25.0063,0.6207,60.0,462.54,536.10,1255.23,1033.59,7.05,...,2028.08,7865.80,10.8366,0.02,305,1915,84.93,14.03,8.6754,321

In [9]:
# Calculate Remaining Useful Life (RUL)
train["RUL"] = train["max_cycle"] - train["cycle"]

train.head()

,unit,cycle,setting1,setting2,setting3,s1,s2,s3,s4,s5,...,s14,s15,s16,s17,s18,s19,s20,s21,max_cycle,RUL
0,1,1,42.0049,0.8400,100.0,445.00,549.68,1343.43,1112.93,3.91,...,8074.83,9.3335,0.02,330,2212,100.00,10.62,6.3670,321,320
1,1,2,20.0020,0.7002,100.0,491.19,606.07,1477.61,1237.50,9.35,...,8046.13,9.1913,0.02,361,2324,100.00,24.37,14.6552,321,319
2,1,3,42.0038,0.8409,100.0,445.00,548.95,1343.12,1117.05,3.91,...,8066.62,9.4007,0.02,329,2212,100.00,10.48,6.4213,321,318
3,1,4,42.0000,0.8400,100.0,445.00,548.70,1341.24,1118.03,3.91,...,8076.05,9.3369,0.02,328,2212,100.00,10.54,6.4176,321,317
4,1,5,25.0063,0.6207,60.0,462.54,536.10,1255.23,1033.59,7.05,...,7865.80,10.8366,0.02,305,1915,84.93,14.03,8.6754,321,316

In [10]:
# Remove the helper column
train.drop(columns="max_cycle", inplace=True)

train.head()

,unit,cycle,setting1,setting2,setting3,s1,s2,s3,s4,s5,...,s13,s14,s15,s16,s17,s18,s19,s20,s21,RUL
0,1,1,42.0049,0.8400,100.0,445.00,549.68,1343.43,1112.93,3.91,...,2387.99,8074.83,9.3335,0.02,330,2212,100.00,10.62,6.3670,320
1,1,2,20.0020,0.7002,100.0,491.19,606.07,1477.61,1237.50,9.35,...,2387.73,8046.13,9.1913,0.02,361,2324,100.00,24.37,14.6552,319
2,1,3,42.0038,0.8409,100.0,445.00,548.95,1343.12,1117.05,3.91,...,2387.97,8066.62,9.4007,0.02,329,2212,100.00,10.48,6.4213,318
3,1,4,42.0000,0.8400,100.0,445.00,548.70,1341.24,1118.03,3.91,...,2388.02,8076.05,9.3369,0.02,328,2212,100.00,10.54,6.4176,317
4,1,5,25.0063,0.6207,60.0,462.54,536.10,1255.23,1033.59,7.05,...,2028.08,7865.80,10.8366,0.02,305,1915,84.93,14.03,8.6754,316

In [11]:
# Check RUL statistics
train["RUL"].describe()

count    61249.000000
mean       133.311417
std         89.783389
min          0.000000
25%         61.000000
50%        122.000000
75%        190.000000
max        542.000000
Name: RUL, dtype: float64

In [12]:
# Check for negative RUL values
print("Negative RUL values:", (train["RUL"] < 0).sum())

Negative RUL values: 0

In [13]:
train.head()

,unit,cycle,setting1,setting2,setting3,s1,s2,s3,s4,s5,...,s13,s14,s15,s16,s17,s18,s19,s20,s21,RUL
0,1,1,42.0049,0.8400,100.0,445.00,549.68,1343.43,1112.93,3.91,...,2387.99,8074.83,9.3335,0.02,330,2212,100.00,10.62,6.3670,320
1,1,2,20.0020,0.7002,100.0,491.19,606.07,1477.61,1237.50,9.35,...,2387.73,8046.13,9.1913,0.02,361,2324,100.00,24.37,14.6552,319
2,1,3,42.0038,0.8409,100.0,445.00,548.95,1343.12,1117.05,3.91,...,2387.97,8066.62,9.4007,0.02,329,2212,100.00,10.48,6.4213,318
3,1,4,42.0000,0.8400,100.0,445.00,548.70,1341.24,1118.03,3.91,...,2388.02,8076.05,9.3369,0.02,328,2212,100.00,10.54,6.4176,317
4,1,5,25.0063,0.6207,60.0,462.54,536.10,1255.23,1033.59,7.05,...,2028.08,7865.80,10.8366,0.02,305,1915,84.93,14.03,8.6754,316

In [14]:
# Save dataset with RUL
train.to_csv(r"D:\Project\aircraft maintenance system\data\processed\train_rul.csv", index=False)

print("train_rul.csv saved successfully!")

train_rul.csv saved successfully!

# Feature Selection

The dataset contains operational settings, sensor measurements, engine identifiers, operating cycles, and the target variable (RUL).

Before training a machine learning model, the input features (X) and target variable (y) are separated.

- `unit` is an engine identifier and does not provide useful predictive information.
- `RUL` is the target variable to be predicted.
- The remaining columns are used as input features for model training.

In [15]:
# Separate features and target

X = train.drop(columns=["unit", "RUL"])
y = train["RUL"]

print("Feature Matrix Shape :", X.shape)
print("Target Vector Shape  :", y.shape)

Feature Matrix Shape : (61249, 25)
Target Vector Shape  : (61249,)

In [16]:
X.columns.tolist()

['cycle',
 'setting1',
 'setting2',
 'setting3',
 's1',
 's2',
 's3',
 's4',
 's5',
 's6',
 's7',
 's8',
 's9',
 's10',
 's11',
 's12',
 's13',
 's14',
 's15',
 's16',
 's17',
 's18',
 's19',
 's20',
 's21']

In [17]:
y.head()

0    320
1    319
2    318
3    317
4    316
Name: RUL, dtype: int64

# Feature Variance Analysis

Not all sensor measurements contribute equally to predicting Remaining Useful Life (RUL). Some sensors may remain nearly constant throughout the engine's operation and provide little useful information.

Variance analysis helps identify features with very low or zero variance, which can be considered for removal to improve model efficiency and reduce noise.