# Preprocessing

# Step 1: Load Clean Dataset

In this step, we load the cleaned NASA CMAPSS FD001 dataset generated during the Exploratory Data Analysis (EDA) phase. We then inspect the dataset structure, dimensions, data types, missing values, and summary statistics before applying preprocessing techniques.

In [1]:
import pandas as pd
import numpy as np

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

In [2]:
train = pd.read_csv(
    r"D:\Project\aircraft maintenance system\data\processed\train_clean.csv",
    index_col=0
)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
# Display first 10 rows
train.head(10)

,cycle,setting1,setting2,setting3,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21
unit,,,,,,,,,,,,,,,,,,,,,,,,,
1,1,42.0049,0.8400,100.0,445.00,549.68,1343.43,1112.93,3.91,5.70,137.36,2211.86,8311.32,1.01,41.69,129.78,2387.99,8074.83,9.3335,0.02,330,2212,100.00,10.62,6.3670
1,2,20.0020,0.7002,100.0,491.19,606.07,1477.61,1237.50,9.35,13.61,332.10,2323.66,8713.60,1.07,43.94,312.59,2387.73,8046.13,9.1913,0.02,361,2324,100.00,24.37,14.6552
1,3,42.0038,0.8409,100.0,445.00,548.95,1343.12,1117.05,3.91,5.69,138.18,2211.92,8306.69,1.01,41.66,129.62,2387.97,8066.62,9.4007,0.02,329,2212,100.00,10.48,6.4213
1,4,42.0000,0.8400,100.0,445.00,548.70,1341.24,1118.03,3.91,5.70,137.98,2211.88,8312.35,1.02,41.68,129.80,2388.02,8076.05,9.3369,0.02,328,2212,100.00,10.54,6.4176
1,5,25.0063,0.6207,60.0,462.54,536.10,1255.23,1033.59,7.05,9.00,174.82,1915.22,7994.94,0.93,36.48,164.11,2028.08,7865.80,10.8366,0.02,305,1915,84.93,14.03,8.6754
1,6,34.9996,0.8400,100.0,449.44,554.77,1352.87,1117.01,5.48,7.97,193.82,2222.77,8340.00,1.02,41.44,181.90,2387.87,8054.10,9.3346,0.02,330,2223,100.00,14.91,8.9057
1,7,0.0019,0.0001,100.0,518.67,641.83,1583.47,1393.89,14.62,21.58,552.45,2387.92,9050.50,1.30,46.94,520.48,2387.89,8127.92,8.3960,0.03,391,2388,100.00,38.93,23.4578
1,8,41.9981,0.8400,100.0,445.00,549.05,1344.16,1110.77,3.91,5.69,137.13,2211.92,8307.28,1.01,41.60,129.65,2387.97,8075.99,9.3679,0.02,329,2212,100.00,10.55,6.2787
1,9,42.0016,0.8400,100.0,445.00,549.55,1342.85,1101.67,3.91,5.70,138.02,2211.90,8307.81,1.02,41.44,129.65,2388.00,8071.13,9.3384,0.02,328,2212,100.00,10.63,6.3055
1,10,25.0019,0.6217,60.0,462.54,536.35,1251.91,1041.37,7.05,9.01,174.70,1915.23,8005.83,0.94,36.24,164.08,2028.13,7869.41,10.9141,0.02,305,1915,84.93,14.34,8.6119

In [4]:
# Dataset dimensions

print(f"Number of Rows    : {train.shape[0]}")
print(f"Number of Columns : {train.shape[1]}")

Number of Rows    : 61249
Number of Columns : 25

In [5]:
# Dataset information

train.info()

<class 'pandas.DataFrame'>
Index: 61249 entries, 1 to 249
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   cycle     61249 non-null  int64
 1   setting1  61249 non-null  float64
 2   setting2  61249 non-null  float64
 3   setting3  61249 non-null  float64
 4   s1        61249 non-null  float64
 5   s2        61249 non-null  float64
 6   s3        61249 non-null  float64
 7   s4        61249 non-null  float64
 8   s5        61249 non-null  float64
 9   s6        61249 non-null  float64
 10  s7        61249 non-null  float64
 11  s8        61249 non-null  float64
 12  s9        61249 non-null  float64
 13  s10       61249 non-null  float64
 14  s11       61249 non-null  float64
 15  s12       61249 non-null  float64
 16  s13       61249 non-null  float64
 17  s14       61249 non-null  float64
 18  s15       61249 non-null  float64
 19  s16       61249 non-null  float64
 20  s17       61249 non-null  int64
 21  s18       61249 non-null  int64
 22  s19       61249 non-null  float64
 23  s20       61249 non-null  float64
 24  s21       61249 non-null  float64
dtypes: float64(22), int64(3)
memory usage: 12.1 MB

In [6]:
# Missing value check
missing = train.isnull().sum()
missing[missing > 0]

Series([], dtype: int64)

In [7]:
# Duplicate rows

print("Duplicate Rows :", train.duplicated().sum())

Duplicate Rows : 0

In [8]:
train.describe().T

            count         mean         std        min        25%        50%        75%        max
cycle     61249.0   134.311417   89.783389     1.0000    62.0000   123.0000   191.0000   543.0000
setting1  61249.0    23.999823   14.780722     0.0000    10.0046    25.0014    41.9981    42.0080
setting2  61249.0     0.571347    0.310703     0.0000     0.2507     0.7000     0.8400     0.8420
setting3  61249.0    94.031576   14.251954    60.0000   100.0000   100.0000   100.0000   100.0000
s1        61249.0   472.882435   26.436832   445.0000   445.0000   462.5400   491.1900   518.6700
s2        61249.0   579.420056   37.342647   535.4800   549.3300   555.7400   607.0700   644.4200
s3        61249.0  1417.896600  106.167598  1242.6700  1350.5500  1367.6800  1497.4200  1613.0000
s4        61249.0  1201.915359  119.327591  1024.4200  1119.4900  1136.9200  1302.6200  1440.7700
s5        61249.0     8.031626    3.622872     3.9100     3.9100     7.0500    10.5200    14.6200
s6        61249.0    11.589457    5.444017     5.6700     5.7200     9.0300    15.4800    21.6100
s7        61249.0   283.328633  146.880210   136.1700   142.9200   194.9600   394.2800   570.8100
s8        61249.0  2228.686034  145.348243  1914.7200  2211.9500  2223.0700  2323.9300  2388.6400
s9        61249.0  8524.673301  336.927547  7984.5100  8320.5900  8362.7600  8777.2500  9196.8100
s10       61249.0     1.096445    0.127681     0.9300     1.0200     1.0300     1.2600     1.3200
s11       61249.0    42.874529    3.243492    36.0400    41.7600    42.3300    45.2200    48.3600
s12       61249.0   266.735665  138.479109   128.3100   134.5200   183.4500   371.4000   537.4900
s13       61249.0  2334.427590  128.197859  2027.5700  2387.9100  2388.0600  2388.1700  2390.4900
s14       61249.0  8067.811812   85.670543  7845.7800  8062.6300  8083.8100  8128.3500  8261.6500
s15       61249.0     9.285604    0.750374     8.1757     8.6480     9.2556     9.3658    11.0663
s16       61249.0     0.023252    0.004685     0.0200     0.0200     0.0200     0.0300     0.0300
s17       61249.0   347.760029   27.808283   302.0000   330.0000   334.0000   368.0000   399.0000
s18       61249.0  2228.613283  145.472491  1915.0000  2212.0000  2223.0000  2324.0000  2388.0000
s19       61249.0    97.751396    5.369424    84.9300   100.0000   100.0000   100.0000   100.0000
s20       61249.0    20.864333    9.936396    10.1600    10.9400    14.9300    28.5600    39.8900
s21       61249.0    12.518995    5.962697     6.0843     6.5661     8.9601    17.1355    23.8852

In [9]:
train.columns.tolist()

['cycle',
 'setting1',
 'setting2',
 'setting3',
 's1',
 's2',
 's3',
 's4',
 's5',
 's6',
 's7',
 's8',
 's9',
 's10',
 's11',
 's12',
 's13',
 's14',
 's15',
 's16',
 's17',
 's18',
 's19',
 's20',
 's21']

# Step 2: Calculate Remaining Useful Life (RUL)

Remaining Useful Life (RUL) is the target variable for predictive maintenance.
For each engine, RUL is calculated as the difference between its maximum operating cycle and the current cycle.

In [10]:

# Step 2: Calculate Remaining Useful Life (RUL)

# Find the maximum cycle for each engine
max_cycle = train.groupby("unit")["cycle"].max().reset_index()

# Rename the column
max_cycle.columns = ["unit", "max_cycle"]

# Merge with original dataset
train = train.merge(max_cycle, on="unit", how="left")

# Calculate RUL
train["RUL"] = train["max_cycle"] - train["cycle"]

# Remove temporary column
train.drop(columns=["max_cycle"], inplace=True)

print("RUL column created successfully.")

RUL column created successfully.

In [11]:
# Preview the new RUL column
train[["unit", "cycle", "RUL"]].head(15)

    unit  cycle  RUL
0      1      1  320
1      1      2  319
2      1      3  318
3      1      4  317
4      1      5  316
5      1      6  315
6      1      7  314
7      1      8  313
8      1      9  312
9      1     10  311
10     1     11  310
11     1     12  309
12     1     13  308
13     1     14  307
14     1     15  306

In [12]:
print("Maximum RUL :", train["RUL"].max())
print("Minimum RUL :", train["RUL"].min())

Maximum RUL : 542
Minimum RUL : 0

# Step 3: Separate Features & Target

In this step, we separate the predictor variables (features) from the target variable (RUL). The `unit` identifier is retained for grouped feature engineering in later steps, while `RUL` is used as the prediction target.

In [13]:

# Step 3: Separate Features & Target
# Target variable
y = train["RUL"]

# Feature matrix
X = train.drop(columns=["RUL"])

print("Feature Matrix Shape :", X.shape)
print("Target Vector Shape  :", y.shape)

Feature Matrix Shape : (61249, 26)
Target Vector Shape  : (61249,)

In [14]:
# First five feature columns
X.head()
# First five feature columns
X.head()

,unit,cycle,setting1,setting2,setting3,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21
0,1,1,42.0049,0.8400,100.0,445.00,549.68,1343.43,1112.93,3.91,5.70,137.36,2211.86,8311.32,1.01,41.69,129.78,2387.99,8074.83,9.3335,0.02,330,2212,100.00,10.62,6.3670
1,1,2,20.0020,0.7002,100.0,491.19,606.07,1477.61,1237.50,9.35,13.61,332.10,2323.66,8713.60,1.07,43.94,312.59,2387.73,8046.13,9.1913,0.02,361,2324,100.00,24.37,14.6552
2,1,3,42.0038,0.8409,100.0,445.00,548.95,1343.12,1117.05,3.91,5.69,138.18,2211.92,8306.69,1.01,41.66,129.62,2387.97,8066.62,9.4007,0.02,329,2212,100.00,10.48,6.4213
3,1,4,42.0000,0.8400,100.0,445.00,548.70,1341.24,1118.03,3.91,5.70,137.98,2211.88,8312.35,1.02,41.68,129.80,2388.02,8076.05,9.3369,0.02,328,2212,100.00,10.54,6.4176
4,1,5,25.0063,0.6207,60.0,462.54,536.10,1255.23,1033.59,7.05,9.00,174.82,1915.22,7994.94,0.93,36.48,164.11,2028.08,7865.80,10.8366,0.02,305,1915,84.93,14.03,8.6754

In [15]:
print("Feature Columns:", len(X.columns))
print("Target Name:", y.name)

Feature Columns: 26
Target Name: RUL

# Step 4: Remove Low Variance Features

Low-variance features contain very little information because their values remain nearly constant across observations. These features are removed to reduce dimensionality, improve computational efficiency, and potentially enhance model performance.

In [16]:
from sklearn.feature_selection import VarianceThreshold

In [17]:
variances = X.drop(columns=["unit", "cycle"]).var().sort_values()

print(variances)

s16              0.000022
s10              0.016302
setting2         0.096537
s15              0.563061
s11             10.520237
s5              13.125202
s19             28.830710
s6              29.637316
s21             35.553759
s20             98.731968
setting3       203.118191
setting1       218.469733
s1             698.906067
s17            773.300629
s2            1394.473263
s14           7339.442015
s3           11271.558809
s4           14239.073899
s13          16434.691116
s12          19176.463675
s8           21126.111710
s18          21162.245693
s7           21573.795950
s9          113520.171620
dtype: float64

In [18]:
# Sensor and setting features only
feature_cols = X.drop(columns=["unit", "cycle"]).columns

In [19]:
# Threshold can be adjusted
threshold = 0.01

selector = VarianceThreshold(threshold=threshold)

selector.fit(X[feature_cols])

VarianceThreshold(threshold=0.01)

In [20]:
selected_features = feature_cols[selector.get_support()]
removed_features = feature_cols[~selector.get_support()]

print("Number of Selected Features :", len(selected_features))
print("Number of Removed Features  :", len(removed_features))

print("\nRemoved Features:")
print(list(removed_features))

Number of Selected Features : 23
Number of Removed Features  : 1

Removed Features:
['s16']

In [21]:
# Keep unit and cycle for future feature engineering
X = pd.concat(
    [
        X[["unit", "cycle"]],
        X[selected_features]
    ],
    axis=1
)

print("Updated Feature Matrix Shape:", X.shape)

Updated Feature Matrix Shape: (61249, 25)

In [22]:
X.head()

,unit,cycle,setting1,setting2,setting3,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s17,s18,s19,s20,s21
0,1,1,42.0049,0.8400,100.0,445.00,549.68,1343.43,1112.93,3.91,5.70,137.36,2211.86,8311.32,1.01,41.69,129.78,2387.99,8074.83,9.3335,330,2212,100.00,10.62,6.3670
1,1,2,20.0020,0.7002,100.0,491.19,606.07,1477.61,1237.50,9.35,13.61,332.10,2323.66,8713.60,1.07,43.94,312.59,2387.73,8046.13,9.1913,361,2324,100.00,24.37,14.6552
2,1,3,42.0038,0.8409,100.0,445.00,548.95,1343.12,1117.05,3.91,5.69,138.18,2211.92,8306.69,1.01,41.66,129.62,2387.97,8066.62,9.4007,329,2212,100.00,10.48,6.4213
3,1,4,42.0000,0.8400,100.0,445.00,548.70,1341.24,1118.03,3.91,5.70,137.98,2211.88,8312.35,1.02,41.68,129.80,2388.02,8076.05,9.3369,328,2212,100.00,10.54,6.4176
4,1,5,25.0063,0.6207,60.0,462.54,536.10,1255.23,1033.59,7.05,9.00,174.82,1915.22,7994.94,0.93,36.48,164.11,2028.08,7865.80,10.8366,305,1915,84.93,14.03,8.6754

In [23]:
X.columns.tolist()
print(X.columns)

Index(['unit', 'cycle', 'setting1', 'setting2', 'setting3', 's1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9',
       's10', 's11', 's12', 's13', 's14', 's15', 's17', 's18', 's19', 's20', 's21'],
      dtype='str')

## Step 5: Cycle-Based Feature Engineering

In [24]:
# Maximum cycle for each engine
max_cycle = X.groupby("unit")["cycle"].transform("max")

# Percentage of life completed
X["cycle_pct"] = X["cycle"] / max_cycle

# Remaining life percentage
X["life_remaining_pct"] = 1 - X["cycle_pct"]

In [25]:
X["max_cycle"] = X.groupby("unit")["cycle"].transform("max")

In [26]:
X["cycle_pct"] = X["cycle"] / X["max_cycle"]

In [27]:
X["life_remaining_pct"] = 1 - X["cycle_pct"]

In [28]:
X["engine_age"] = X["cycle"]

In [29]:
X[[
    "unit",
    "cycle",
    "max_cycle",
    "cycle_pct",
    "life_remaining_pct",
    "engine_age"
]].head(10)

   unit  cycle  max_cycle  cycle_pct  life_remaining_pct  engine_age
0     1      1        321   0.003115            0.996885           1
1     1      2        321   0.006231            0.993769           2
2     1      3        321   0.009346            0.990654           3
3     1      4        321   0.012461            0.987539           4
4     1      5        321   0.015576            0.984424           5
5     1      6        321   0.018692            0.981308           6
6     1      7        321   0.021807            0.978193           7
7     1      8        321   0.024922            0.975078           8
8     1      9        321   0.028037            0.971963           9
9     1     10        321   0.031153            0.968847          10

In [30]:
X.drop(columns=["max_cycle"], inplace=True)

## Step 6: Rolling Mean Features

In [31]:
sensor_cols = [
    col for col in X.columns
    if col.startswith("s") and col[1:].isdigit()
]

for col in sensor_cols:
    X[f"{col}_roll_mean"] = (
        X.groupby("unit")[col]
        .transform(lambda x: x.rolling(window=5, min_periods=1).mean())
    )

In [32]:
len([col for col in X.columns if "roll_mean" in col])

20

In [33]:
roll_mean_cols = [col for col in X.columns if "roll_mean" in col]

X[roll_mean_cols].head()

,s1_roll_mean,s2_roll_mean,s3_roll_mean,s4_roll_mean,s5_roll_mean,s6_roll_mean,s7_roll_mean,s8_roll_mean,s9_roll_mean,s10_roll_mean,s11_roll_mean,s12_roll_mean,s13_roll_mean,s14_roll_mean,s15_roll_mean,s17_roll_mean,s18_roll_mean,s19_roll_mean,s20_roll_mean,s21_roll_mean
0,445.000000,549.680000,1343.430000,1112.930000,3.910000,5.700000,137.360000,2211.860000,8311.32,1.0100,41.6900,129.780000,2387.990000,8074.830000,9.3335,330.0,2212.000000,100.000,10.620000,6.367000
1,468.095000,577.875000,1410.520000,1175.215000,6.630000,9.655000,234.730000,2267.760000,8512.46,1.0400,42.8150,221.185000,2387.860000,8060.480000,9.2624,345.5,2268.000000,100.000,17.495000,10.511100
2,460.396667,568.233333,1388.053333,1155.826667,5.723333,8.333333,202.546667,2249.146667,8443.87,1.0300,42.4300,190.663333,2387.896667,8062.526667,9.3085,340.0,2249.333333,100.000,15.156667,9.147833
3,456.547500,563.350000,1376.350000,1146.377500,5.270000,7.675000,186.405000,2239.830000,8410.99,1.0275,42.2425,175.447500,2387.927500,8065.907500,9.3156,337.0,2240.000000,100.000,14.002500,8.465275
4,457.746000,557.900000,1352.126000,1123.820000,5.626000,7.940000,184.088000,2174.908000,8327.78,1.0080,41.0900,173.180000,2315.958000,8025.886000,9.6198,330.6,2175.000000,96.986,14.008000,8.507300

In [34]:
[col for col in X.columns if "roll_mean_roll_mean" in col]

[]

In [35]:
for col in sensor_cols:
    X[f"{col}_roll_std"] = (
        X.groupby("unit")[col]
        .transform(
            lambda x: x.rolling(window=5, min_periods=1).std()
        )
        .fillna(0)
    )

## step 7: Rolling Standard Deviation

In [36]:
std_cols = [col for col in X.columns if "roll_std" in col]

print(std_cols)

['s1_roll_std', 's2_roll_std', 's3_roll_std', 's4_roll_std', 's5_roll_std', 's6_roll_std', 's7_roll_std', 's8_roll_std', 's9_roll_std', 's10_roll_std', 's11_roll_std', 's12_roll_std', 's13_roll_std', 's14_roll_std', 's15_roll_std', 's17_roll_std', 's18_roll_std', 's19_roll_std', 's20_roll_std', 's21_roll_std']

In [37]:
X[std_cols].head()

,s1_roll_std,s2_roll_std,s3_roll_std,s4_roll_std,s5_roll_std,s6_roll_std,s7_roll_std,s8_roll_std,s9_roll_std,s10_roll_std,s11_roll_std,s12_roll_std,s13_roll_std,s14_roll_std,s15_roll_std,s17_roll_std,s18_roll_std,s19_roll_std,s20_roll_std,s21_roll_std
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,32.661262,39.873751,94.879588,88.084292,3.846661,5.593215,137.701975,79.054538,284.454916,0.042426,1.590990,129.266191,0.183848,20.293965,0.100551,21.920310,79.195959,0.000000,9.722718,5.860642
2,26.667809,32.769547,77.558503,70.761173,3.140785,4.569730,112.197227,64.530447,233.604503,0.034641,1.307784,105.591621,0.144684,14.781375,0.106915,18.193405,64.663230,0.000000,7.979288,4.769597
3,23.095000,28.483035,67.513601,60.788508,2.720000,3.956669,97.130627,55.886672,201.755017,0.028723,1.131735,91.428369,0.133260,13.833998,0.088443,16.020820,56.000000,0.000000,6.911905,4.126691
4,20.179601,27.513178,79.703047,72.908409,2.486459,3.477434,84.276993,153.025555,255.241720,0.050200,2.757154,79.341463,160.928736,90.289185,0.684511,19.932386,153.222061,6.739509,5.985898,3.575054

In [38]:
len(std_cols)

20

## Step 8: Lag Features

In [39]:
for col in sensor_cols:
    X[f"{col}_lag1"] = (
        X.groupby("unit")[col]
        .shift(1)
        .fillna(0)
    )

In [40]:
lag_cols = [col for col in X.columns if "_lag1" in col]

print(lag_cols)

['s1_lag1', 's2_lag1', 's3_lag1', 's4_lag1', 's5_lag1', 's6_lag1', 's7_lag1', 's8_lag1', 's9_lag1', 's10_lag1', 's11_lag1', 's12_lag1', 's13_lag1', 's14_lag1', 's15_lag1', 's17_lag1', 's18_lag1', 's19_lag1', 's20_lag1', 's21_lag1']

In [41]:
X[lag_cols].head()

,s1_lag1,s2_lag1,s3_lag1,s4_lag1,s5_lag1,s6_lag1,s7_lag1,s8_lag1,s9_lag1,s10_lag1,s11_lag1,s12_lag1,s13_lag1,s14_lag1,s15_lag1,s17_lag1,s18_lag1,s19_lag1,s20_lag1,s21_lag1
0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.0,0.0,0.0,0.00,0.0000
1,445.00,549.68,1343.43,1112.93,3.91,5.70,137.36,2211.86,8311.32,1.01,41.69,129.78,2387.99,8074.83,9.3335,330.0,2212.0,100.0,10.62,6.3670
2,491.19,606.07,1477.61,1237.50,9.35,13.61,332.10,2323.66,8713.60,1.07,43.94,312.59,2387.73,8046.13,9.1913,361.0,2324.0,100.0,24.37,14.6552
3,445.00,548.95,1343.12,1117.05,3.91,5.69,138.18,2211.92,8306.69,1.01,41.66,129.62,2387.97,8066.62,9.4007,329.0,2212.0,100.0,10.48,6.4213
4,445.00,548.70,1341.24,1118.03,3.91,5.70,137.98,2211.88,8312.35,1.02,41.68,129.80,2388.02,8076.05,9.3369,328.0,2212.0,100.0,10.54,6.4176

## Step 8: Delta Features
Delta = Current Value - Previous Value

In [42]:
for col in sensor_cols:
    X[f"{col}_delta"] = X[col] - X[f"{col}_lag1"]

C:\Users\monda\AppData\Local\Temp\ipykernel_19740\3522375938.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  X[f"{col}_delta"] = X[col] - X[f"{col}_lag1"]
C:\Users\monda\AppData\Local\Temp\ipykernel_19740\3522375938.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  X[f"{col}_delta"] = X[col] - X[f"{col}_lag1"]
C:\Users\monda\AppData\Local\Temp\ipykernel_19740\3522375938.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  X[f"{col}_delta"] = X[col] - X[f"{col}_lag1"]
C:\Users\monda\AppData\Local\Temp\ipykernel_19740\3522375938.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  X[f"{col}_delta"] = X[col] - X[f"{col}_lag1"]
C:\Users\monda\AppData\Local\Temp\ipykernel_19740\3522375938.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  X[f"{col}_delta"] = X[col] - X[f"{col}_lag1"]
C:\Users\monda\AppData\Local\Temp\ipykernel_19740\3522375938.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  X[f"{col}_delta"] = X[col] - X[f"{col}_lag1"]
C:\Users\monda\AppData\Local\Temp\ipykernel_19740\3522375938.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  X[f"{col}_delta"] = X[col] - X[f"{col}_lag1"]
C:\Users\monda\AppData\Local\Temp\ipykernel_19740\3522375938.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  X[f"{col}_delta"] = X[col] - X[f"{col}_lag1"]

In [43]:
delta_cols = [col for col in X.columns if "_delta" in col]

print(delta_cols)
print(len(delta_cols))

['s1_delta', 's2_delta', 's3_delta', 's4_delta', 's5_delta', 's6_delta', 's7_delta', 's8_delta', 's9_delta', 's10_delta', 's11_delta', 's12_delta', 's13_delta', 's14_delta', 's15_delta', 's17_delta', 's18_delta', 's19_delta', 's20_delta', 's21_delta']
20

In [44]:
X[delta_cols].head()

,s1_delta,s2_delta,s3_delta,s4_delta,s5_delta,s6_delta,s7_delta,s8_delta,s9_delta,s10_delta,s11_delta,s12_delta,s13_delta,s14_delta,s15_delta,s17_delta,s18_delta,s19_delta,s20_delta,s21_delta
0,445.00,549.68,1343.43,1112.93,3.91,5.70,137.36,2211.86,8311.32,1.01,41.69,129.78,2387.99,8074.83,9.3335,330.0,2212.0,100.00,10.62,6.3670
1,46.19,56.39,134.18,124.57,5.44,7.91,194.74,111.80,402.28,0.06,2.25,182.81,-0.26,-28.70,-0.1422,31.0,112.0,0.00,13.75,8.2882
2,-46.19,-57.12,-134.49,-120.45,-5.44,-7.92,-193.92,-111.74,-406.91,-0.06,-2.28,-182.97,0.24,20.49,0.2094,-32.0,-112.0,0.00,-13.89,-8.2339
3,0.00,-0.25,-1.88,0.98,0.00,0.01,-0.20,-0.04,5.66,0.01,0.02,0.18,0.05,9.43,-0.0638,-1.0,0.0,0.00,0.06,-0.0037
4,17.54,-12.60,-86.01,-84.44,3.14,3.30,36.84,-296.66,-317.41,-0.09,-5.20,34.31,-359.94,-210.25,1.4997,-23.0,-297.0,-15.07,3.49,2.2578

In [45]:
from sklearn.preprocessing import StandardScaler

# Save unit separately
unit = X["unit"]

# Remove unit before scaling
X_no_unit = X.drop(columns=["unit"])

# Scale remaining features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_no_unit)

# Convert back to DataFrame
X_scaled = pd.DataFrame(X_scaled, columns=X_no_unit.columns)

# Add unit back
X_scaled.insert(0, "unit", unit.values)

# Add target
X_scaled["RUL"] = y.values

In [46]:
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

In [47]:
X_scaled.head(10)

,unit,cycle,setting1,setting2,setting3,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s17,s18,s19,s20,s21,cycle_pct,life_remaining_pct,engine_age,s1_roll_mean,s2_roll_mean,s3_roll_mean,s4_roll_mean,s5_roll_mean,s6_roll_mean,s7_roll_mean,s8_roll_mean,s9_roll_mean,s10_roll_mean,s11_roll_mean,s12_roll_mean,s13_roll_mean,s14_roll_mean,s15_roll_mean,s17_roll_mean,s18_roll_mean,s19_roll_mean,s20_roll_mean,s21_roll_mean,s1_roll_std,s2_roll_std,s3_roll_std,s4_roll_std,s5_roll_std,s6_roll_std,s7_roll_std,s8_roll_std,s9_roll_std,s10_roll_std,s11_roll_std,s12_roll_std,s13_roll_std,s14_roll_std,s15_roll_std,s17_roll_std,s18_roll_std,s19_roll_std,s20_roll_std,s21_roll_std,s1_lag1,s2_lag1,s3_lag1,s4_lag1,s5_lag1,s6_lag1,s7_lag1,s8_lag1,s9_lag1,s10_lag1,s11_lag1,s12_lag1,s13_lag1,s14_lag1,s15_lag1,s17_lag1,s18_lag1,s19_lag1,s20_lag1,s21_lag1,s1_delta,s2_delta,s3_delta,s4_delta,s5_delta,s6_delta,s7_delta,s8_delta,s9_delta,s10_delta,s11_delta,s12_delta,s13_delta,s14_delta,s15_delta,s17_delta,s18_delta,s19_delta,s20_delta,s21_delta
0,1,-1.484824,1.218156,0.864668,0.418783,-1.054690,-0.796416,-0.701412,-0.745729,-1.137677,-1.081831,-0.993802,-0.115765,-0.633237,-0.677047,-0.365205,-0.989007,0.417814,0.081921,0.063831,-0.638665,-0.114203,0.418783,-1.030999,-1.031756,-1.728313,1.728313,-1.484824,-2.342813,-1.767610,-1.546081,-1.637102,-2.525322,-2.402004,-2.205596,-0.254537,-1.393538,-1.496627,-0.793528,-2.194965,0.918236,0.178869,0.137752,-1.407779,-0.251153,0.920299,-2.288422,-2.290086,-3.263796,-3.282530,-3.310930,-3.169644,-3.040016,-2.963122,-2.869501,-2.055763,-3.275091,-2.877852,-2.622864,-2.867457,-1.093058,-1.752509,-2.104915,-3.303470,-2.054453,-1.091995,-2.958860,-2.958758,-11.771074,-11.007450,-10.144644,-8.455889,-2.193515,-2.107651,-1.912397,-10.935154,-13.301256,-7.514812,-10.082140,-1.909660,-11.852932,-15.439162,-9.690003,-9.755151,-10.930175,-11.851689,-2.079062,-2.078849,9.226774,8.490698,7.641208,5.987512,0.752417,0.730048,0.652478,8.830117,11.479213,5.195082,7.804711,0.653891,10.170576,15.276723,7.675810,7.284528,8.825518,10.169474,0.745499,0.744810
1,1,-1.473686,-0.270478,0.414718,0.418783,0.692508,0.713666,0.562449,0.298212,0.363906,0.371152,0.332051,0.653429,0.560738,-0.207120,0.328498,0.331131,0.415786,-0.253086,-0.125677,0.476120,0.655708,0.418783,0.352814,0.358264,-1.717521,1.717521,-1.473686,-0.402992,-0.091718,-0.150756,-0.488788,-0.859484,-0.789598,-0.734638,0.593511,-0.077558,-0.976872,-0.035328,-0.730330,0.916010,-0.170439,-0.068297,-0.176906,0.597692,0.920299,-0.753209,-0.747992,0.955240,0.382776,-0.214965,-0.709657,0.360017,0.251428,-0.019078,-0.810280,-0.377929,-1.864422,-1.239891,-0.031132,-1.090927,-1.265229,-1.790857,-0.578331,-0.808456,-1.091995,0.098798,0.112580,-0.649746,-0.522893,-0.493509,-0.593875,-1.122042,-1.067502,-0.982003,-0.037969,-0.279941,-0.564139,-0.237720,-0.977259,0.322297,0.076944,0.089143,-0.460368,-0.036913,0.322954,-1.017134,-1.017899,0.922560,0.838654,0.733523,0.646581,1.048896,1.015081,0.927017,0.411616,0.509851,0.286896,0.389592,0.923013,-0.042385,-0.117256,-0.148114,0.655877,0.412183,-0.041259,0.966723,0.971092
2,1,-1.462548,1.218082,0.867565,0.418783,-1.054690,-0.815965,-0.704332,-0.711202,-1.137677,-1.083668,-0.988219,-0.115352,-0.646979,-0.677047,-0.374454,-0.990162,0.417658,-0.013912,0.153387,-0.674626,-0.114203,0.418783,-1.045089,-1.022649,-1.706729,1.706729,-1.462548,-1.049599,-0.664813,-0.618013,-0.846240,-1.414763,-1.328425,-1.220828,0.311132,-0.526315,-1.150124,-0.294801,-1.219396,0.916638,-0.120619,0.065302,-0.613668,0.314744,0.920299,-1.275367,-1.255288,0.181033,-0.270262,-0.780160,-1.193451,-0.263901,-0.336792,-0.547025,-1.039103,-0.895839,-2.050390,-1.486068,-0.550593,-1.091381,-1.397592,-1.770978,-1.041661,-1.037100,-1.091995,-0.449487,-0.459195,0.504623,0.552686,0.470433,0.286118,0.368704,0.375932,0.337049,0.512837,0.350310,-0.151228,0.293582,0.336135,0.320972,0.021796,-0.059847,0.412778,0.514644,0.322954,0.357773,0.363186,-1.001021,-0.922143,-0.801220,-0.677466,-1.059396,-1.026575,-0.932561,-0.484488,-0.612447,-0.333086,-0.462094,-0.933284,-0.040246,-0.023812,0.142196,-0.740795,-0.485239,-0.041259,-0.986839,-0.974909
3,1,-1.451410,1.217824,0.864668,0.418783,-1.054690,-0.822660,-0.722040,-0.702990,-1.137677,-1.081831,-0.989581,-0.115627,-0.630180,-0.598726,-0.368288,-0.988862,0.418048,0.096162,0.068362,-0.710586,-0.114203,0.418783,-1.039051,-1.023269,-1.695938,1.695938,-1.451410,-1.372903,-0.955075,-0.861417,-1.020449,-1.692403,-1.596820,-1.464679,0.169790,-0.741436,-1.193437,-0.421167,-1.463208,0.917166,-0.038323,0.085877,-0.851901,0.173270,0.920299,-1.533097,-1.509280,-0.280487,-0.664290,-1.107930,-1.471964,-0.635830,-0.689133,-0.858903,-1.175283,-1.220225,-2.191756,-1.639099,-0.861360,-1.091514,-1.420339,-1.828673,-1.311758,-1.173400,-1.091995,-0.785164,-0.796117,-0.649746,-0.536817,-0.495736,-0.564770,-1.122042,-1.069327,-0.976449,-0.037674,-0.287194,-0.564139,-0.244804,-0.978408,0.322195,0.061168,0.159551,-0.488534,-0.036913,0.322954,-1.031133,-1.008851,-0.039230,-0.039960,-0.043703,-0.021278,-0.005250,-0.003813,-0.005690,-0.036717,-0.040237,0.028570,-0.029671,-0.003816,-0.041059,-0.044822,-0.083381,-0.053544,-0.036528,-0.041259,-0.000870,-0.005542
4,1,-1.440272,0.068094,0.158844,-2.387873,-0.391216,-1.160079,-1.532181,-1.410627,-0.270955,-0.475656,-0.738762,-2.156673,-1.572260,-1.303616,-1.971512,-0.741097,-2.389666,-2.358027,2.066982,-1.537685,-2.155843,-2.387873,-0.687814,-0.644612,-1.685146,1.685146,-1.440272,-1.272237,-1.279019,-1.365223,-1.436329,-1.474374,-1.488783,-1.499681,-0.815128,-1.285847,-1.531278,-1.197901,-1.499542,-0.314847,-1.012527,0.967451,-1.360133,-0.811996,-0.311573,-1.531869,-1.493642,-0.657085,-0.753442,-0.710183,-1.133484,-0.842254,-0.964560,-1.124972,0.355115,-0.675465,-1.678745,-0.226199,-1.126567,0.772199,0.415431,0.033078,-0.825471,0.356204,0.772036,-1.076380,-1.085209,-0.649746,-0.541585,-0.509242,-0.557848,-1.122042,-1.067502,-0.977804,-0.037871,-0.278327,-0.495321,-0.240081,-0.977115,0.322450,0.079288,0.092705,-0.516700,-0.036913,0.322954,-1.025133,-1.009467,0.325996,-0.231537,-0.524285,-0.482874,0.603209,0.420511,0.171531,-1.225776,-0.488315,-0.488081,-1.011083,0.169390,-1.580497,-0.462140,1.207575,-0.541271,-1.226414,-1.580017,0.241559,0.260821
5,1,-1.429134,0.744204,0.864668,0.418783,-0.886741,-0.660110,-0.612495,-0.711537,-0.704316,-0.664856,-0.609404,-0.040703,-0.548114,-0.598726,-0.442283,-0.612629,0.416878,-0.160054,0.065297,-0.638665,-0.038587,0.418783,-0.599250,-0.605988,-1.674354,1.674354,-1.429134,-1.197651,-1.218510,-1.325957,-1.421285,-1.282068,-1.303692,-1.329094,-0.782025,-1.248318,-1.496627,-1.231599,-1.332512,-0.315258,-1.113449,0.968089,-1.360133,-0.778649,-0.311573,-1.340274,-1.304702,-0.736233,-0.779872,-0.714941,-1.137104,-0.999699,-1.093661,-1.210788,0.366689,-0.676892,-1.671629,-0.236071,-1.209823,0.772043,0.358661,0.032720,-0.825471,0.367866,0.772036,-1.173075,-1.192956,-0.211390,-0.781917,-1.127133,-1.154353,-0.261574,-0.465311,-0.728272,-1.499427,-0.775612,-1.114688,-1.467977,-0.730616,-1.512713,-0.324715,1.664011,-1.164518,-1.499526,-1.511764,-0.676157,-0.633244,-0.312005,0.253532,0.524792,0.424213,-0.309480,-0.137945,0.086174,1.196318,0.430490,0.441891,0.899099,0.085553,1.497310,0.294971,-1.270878,0.522860,1.197428,1.497498,0.057087,0.022019
6,1,-1.417996,-1.623609,-1.838575,0.418783,1.731975,1.671292,1.559560,1.608817,1.818565,1.835157,1.832266,1.095543,1.560665,1.594265,1.253434,1.832380,0.417034,0.701626,-1.185557,1.554944,1.095657,0.418783,1.818146,1.834555,-1.663563,1.663563,-1.417996,-0.736025,-0.793400,-0.885625,-0.844630,-0.636556,-0.653837,-0.663333,-0.587050,-0.807477,-0.699670,-0.827226,-0.666283,-0.314710,-0.715262,0.507132,-0.883666,-0.584627,-0.311573,-0.690014,-0.649581,0.782539,0.660593,0.700436,0.681305,0.899836,0.852220,0.786543,0.635364,0.693154,0.502781,0.593303,0.788227,0.772250,0.656524,0.627611,0.692803,0.635008,0.772036,0.812774,0.808455,-0.538782,-0.425806,-0.425693,-0.565053,-0.691808,-0.653268,-0.599577,0.015781,-0.235008,-0.495321,-0.296753,-0.602804,0.321686,0.037111,0.090295,-0.460368,0.017257,0.322954,-0.588163,-0.594869,1.402310,1.314415,1.284309,1.469639,1.765870,1.750231,1.711164,0.625480,0.937334,1.423528,1.000625,1.713530,-0.041187,0.077497,-0.805688,1.320959,0.624520,-0.041259,1.692595,1.708864
7,1,-1.406858,1.217696,0.864668,0.418783,-1.054690,-0.813287,-0.694536,-0.763831,-1.137677,-1.083668,-0.995368,-0.115352,-0.645228,-0.677047,-0.392953,-0.989946,0.417658,0.095462,0.109675,-0.674626,-0.114203,0.418783,-1.038044,-1.046564,-1.652771,1.652771,-1.406858,-0.736025,-0.792211,-0.881300,-0.867786,-0.636556,-0.653837,-0.666506,-0.587050,-0.806705,-0.699670,-0.835313,-0.666187,-0.314710,-0.669645,0.488121,-0.883666,-0.584627,-0.311573,-0.686888,-0.660194,0.782539,0.659678,0.698251,0.694440,0.899836,0.852220,0.789670,0.635364,0.692791,0.502781,0.593317,0.788133,0.772250,0.674548,0.629758,0.692803,0.635008,0.772036,0.809436,0.819903,1.191396,1.234770,1.230926,1.390896,1.812864,1.830316,1.829568,0.829427,0.878130,1.431598,1.001983,1.829716,0.321787,0.178959,-0.893120,1.257759,0.829820,0.322954,1.813674,1.829986,-1.573222,-1.475310,-1.399991,-1.556507,-2.080599,-2.054496,-1.991869,-0.742087,-1.078888,-1.521383,-1.037405,-1.988153,-0.040931,-0.161385,0.771779,-1.405877,-0.741646,-0.041259,-2.010975,-2.028490
8,1,-1.395720,1.217933,0.864668,0.418783,-1.054690,-0.799898,-0.706875,-0.840092,-1.137677,-1.081831,-0.989308,-0.115489,-0.643655,-0.598726,-0.442283,-0.989946,0.417892,0.038732,0.070361,-0.710586,-0.114203,0.418783,-1.029993,-1.042070,-1.641979,1.641979,-1.395720,-0.736025,-0.782106,-0.874603,-0.928110,-0.636556,-0.653837,-0.666385,-0.586989,-0.812646,-0.699670,-0.867663,-0.666668,-0.314779,-0.693598,0.488990,-0.883666,-0.584627,-0.311573,-0.682868,-0.668537,0.782539,0.651904,0.694667,0.729918,0.899836,0.852220,0.789552,0.635375,0.695475,0.502781,0.593937,0.788604,0.772224,0.664561,0.629602,0.692803,0.635008,0.772036,0.805172,0.828803,-0.649746,-0.534909,-0.488265,-0.609134,-1.122042,-1.069327,-0.983561,-0.037674,-0.286270,-0.564139,-0.258972,-0.978193,0.322195,0.079173,0.125185,-0.488534,-0.036913,0.322954,-1.024133,-1.032613,-0.039230,-0.028326,-0.040447,-0.075749,-0.005250,-0.003813,-0.000475,-0.036636,-0.047352,0.028570,-0.063512,-0.004730,-0.041144,-0.071968,-0.055060,-0.053544,-0.036528,-0.041259,0.000544,-0.001950
9,1,-1.384582,0.067797,0.162063,-2.387873,-0.391216,-1.153384,-1.563452,-1.345428,-0.270955,-0.473819,-0.739579,-2.156604,-1.539938,-1.225295,-2.045507,-0.741314,-2.389276,-2.315889,2.170265,-1.537685,-2.155843,-2.387873,-0.656615,-0.655262,-1.631188,1.631188,-1.384582,-0.736025,-0.779134,-0.888412,-0.899423,-0.636556,-0.653022,-0.666748,-0.586959,-0.798396,-0.665019,-0.900013,-0.666764,-0.314608,-0.676023,0.533909,-0.883666,-0.584627,-0.311573,-0.669023,-0.673263,0.782539,0.647867,0.721453,0.685045,0.899836,0.852007,0.789778,0.635311,0.666864,0.450905,0.666352,0.788665,0.771965,0.627303,0.725579,0.692803,0.635008,0.772036,0.797720,0.831190,-0.649746,-0.525372,-0.497676,-0.673419,-1.122042,-1.067502,-0.977533,-0.037772,-0.285440,-0.495321,-0.296753,-0.978193,0.322348,0.069834,0.094277,-0.516700,-0.036913,0.322954,-1.016134,-1.028147,0.325996,-0.240844,-0.552447,-0.352425,0.603209,0.421801,0.170765,-1.225816,-0.466915,-0.436416,-1.011083,0.169999,-1.580198,-0.445936,1.270326,-0.541271,-1.226414,-1.580017,0.257108,0.266545

In [48]:
import pandas as pd

X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

In [49]:
X_scaled["RUL"] = y.values

In [50]:
import os
print(os.getcwd())
print(os.listdir())

d:\Project\aircraft maintenance system\notebook
['01_EDA.ipynb', '02preprocessing.ipynb', '03_Model_Training']

In [51]:
X_scaled.to_csv(
    r"D:\Project\aircraft maintenance system\data\processed\train_processed.csv",
    index=False
)

print("✅ Saved successfully!")

✅ Saved successfully!